import sqlite3

conn = sqlite3.connect("database.db")
c = conn.cursor()

# Clear old questions
c.execute("DELETE FROM questions")


cse_questions = [

("CSE","Which data structure follows FIFO principle?","Stack","Queue","Heap","Tree","Queue"),
("CSE","Which data structure follows LIFO principle?","Queue","Stack","Tree","Graph","Stack"),
("CSE","Time complexity of Binary Search?","O(n)","O(log n)","O(n^2)","O(1)","O(log n)"),
("CSE","Which sorting algorithm is stable?","Quick Sort","Heap Sort","Merge Sort","Selection Sort","Merge Sort"),
("CSE","Which traversal of BST gives sorted output?","Preorder","Postorder","Inorder","Level Order","Inorder"),
("CSE","Which algorithm is used to find shortest path in weighted graph?","DFS","BFS","Dijkstra","Prim","Dijkstra"),
("CSE","Which algorithm is used for Minimum Spanning Tree?","Dijkstra","Kruskal","Binary Search","DFS","Kruskal"),
("CSE","Which layer of OSI handles routing?","Transport","Network","Session","Data Link","Network"),
("CSE","Which protocol is connection-oriented?","UDP","TCP","IP","ICMP","TCP"),
("CSE","Which memory is fastest?","RAM","ROM","Cache","Hard Disk","Cache"),
("CSE","Which scheduling algorithm uses time quantum?","FCFS","SJF","Round Robin","Priority","Round Robin"),
("CSE","Which normal form removes transitive dependency?","1NF","2NF","3NF","BCNF","3NF"),
("CSE","Which key uniquely identifies a record?","Foreign Key","Candidate Key","Primary Key","Composite Key","Primary Key"),
("CSE","Which algorithm uses divide and conquer?","Bubble Sort","Insertion Sort","Merge Sort","Linear Search","Merge Sort"),
("CSE","Which is NOT a NoSQL database?","MongoDB","Cassandra","MySQL","Redis","MySQL"),
("CSE","Which data structure is used in BFS?","Stack","Queue","Heap","Tree","Queue"),
("CSE","Which is not OOP concept?","Encapsulation","Inheritance","Polymorphism","Compilation","Compilation"),
("CSE","Which port number is used for HTTP?","21","25","80","110","80"),
("CSE","Which hashing technique resolves collision by probing?","Chaining","Open Addressing","Mapping","Hash Tree","Open Addressing"),
("CSE","Which is volatile memory?","ROM","SSD","RAM","CD","RAM"),
("CSE","Which algorithm detects cycle in graph?","DFS","Binary Search","Quick Sort","Prim","DFS"),
("CSE","Which is used for version control?","Git","Linux","Windows","Chrome","Git"),
("CSE","Which protocol converts domain to IP?","FTP","DNS","SMTP","ARP","DNS"),
("CSE","Which complexity is best case of Quick Sort?","O(n^2)","O(n log n)","O(n)","O(log n)","O(n log n)"),
("CSE","Which is a linear data structure?","Tree","Graph","Stack","Heap","Stack"),
("CSE","Which symbol is used for single line comment in Python?","//","#","/* */","--","#"),
("CSE","Which SQL command is used to retrieve data?","INSERT","UPDATE","SELECT","DELETE","SELECT"),
("CSE","Which deadlock condition is necessary?","Mutual Exclusion","Sharing","Duplication","Cloning","Mutual Exclusion"),
("CSE","Which algorithm is greedy?","Dijkstra","DFS","Binary Search","Merge","Dijkstra"),
("CSE","Which device connects different networks?","Switch","Hub","Router","Repeater","Router"),
("CSE","Which is a compiled language?","Python","Java","HTML","CSS","Java"),
("CSE","Which is not relational DB?","Oracle","MySQL","MongoDB","PostgreSQL","MongoDB"),
("CSE","Which OS manages hardware resources?","Compiler","Operating System","Browser","IDE","Operating System"),
("CSE","Which algorithm is used in Page Replacement?","FIFO","Binary Search","DFS","Heap","FIFO"),
("CSE","Which protocol is used for sending email?","HTTP","SMTP","FTP","DNS","SMTP"),
("CSE","Which is not a programming paradigm?","OOP","Functional","Procedural","Scanning","Scanning"),
("CSE","Which data structure is used in recursion?","Queue","Stack","Heap","Graph","Stack"),
("CSE","Which command removes table in SQL?","DROP","DELETE","REMOVE","CLEAR","DROP"),
("CSE","Which is symmetric encryption?","RSA","AES","ECC","DSA","AES"),
("CSE","Which algorithm is used for searching in sorted array?","Linear","Binary","DFS","Prim","Binary"),
("CSE","Which protocol secures HTTP?","FTP","HTTPS","SMTP","TELNET","HTTPS"),
("CSE","Which is not a Linux OS?","Ubuntu","Fedora","Windows","Debian","Windows"),
("CSE","Which data structure stores hierarchical data?","Stack","Queue","Tree","Array","Tree"),
("CSE","Which algorithm is used for topological sorting?","DFS","Binary Search","Prim","Kruskal","DFS"),
("CSE","Which SQL clause filters rows?","ORDER BY","GROUP BY","WHERE","SELECT","WHERE"),
("CSE","Which is example of dynamic programming?","Fibonacci","Bubble Sort","Linear Search","Stack","Fibonacci"),
("CSE","Which protocol is used for file transfer?","HTTP","FTP","SMTP","SNMP","FTP"),
("CSE","Which language is mainly used for Android development?","Swift","Java","Kotlin","C#","Kotlin"),
("CSE","Which layer handles encryption in OSI?","Presentation","Transport","Network","Physical","Presentation"),
("CSE","Which command creates table in SQL?","CREATE","MAKE","NEW","BUILD","CREATE")

]


# ========================= ECE (50) =========================

ece_questions = [

("ECE","Unit of electrical resistance?","Volt","Ohm","Ampere","Watt","Ohm"),
("ECE","Ohm’s law states?","V = IR","P = VI","I = V/R^2","R = VI","V = IR"),
("ECE","Which material is semiconductor?","Copper","Iron","Silicon","Aluminum","Silicon"),
("ECE","Which device amplifies signals?","Diode","Resistor","Transistor","Capacitor","Transistor"),
("ECE","Unit of capacitance?","Henry","Farad","Tesla","Weber","Farad"),
("ECE","Unit of inductance?","Farad","Henry","Ohm","Volt","Henry"),
("ECE","Which converts AC to DC?","Oscillator","Rectifier","Amplifier","Transformer","Rectifier"),
("ECE","Which device stores charge?","Resistor","Capacitor","Inductor","Battery","Capacitor"),
("ECE","Binary number system base?","2","8","10","16","2"),
("ECE","Which logic gate gives output 1 only if both inputs are 1?","OR","AND","XOR","NOR","AND"),
("ECE","Full form of LED?","Light Emitting Diode","Low Energy Device","Linear Emitting Device","None","Light Emitting Diode"),
("ECE","Which instrument measures voltage?","Ammeter","Voltmeter","Wattmeter","Ohmmeter","Voltmeter"),
("ECE","Which law is used in nodal analysis?","Ohm’s Law","Kirchhoff’s Current Law","Faraday’s Law","Coulomb’s Law","Kirchhoff’s Current Law"),
("ECE","Which amplifier configuration has high input impedance?","CE","CB","CC","None","CC"),
("ECE","Unit of frequency?","Hertz","Volt","Ohm","Tesla","Hertz"),
("ECE","Which modulation has better noise immunity?","AM","FM","ASK","FSK","FM"),
("ECE","Which device converts digital to analog?","ADC","DAC","CPU","ROM","DAC"),
("ECE","Flip-flop stores how many bits?","1","2","4","8","1"),
("ECE","Which is an active component?","Resistor","Capacitor","Transistor","Inductor","Transistor"),
("ECE","Which law relates charge and current?","Faraday","Coulomb","Ampere","Ohm","Coulomb"),
("ECE","Binary addition of 1 + 1 equals?","1","10","11","0","10"),
("ECE","Which device works as voltage regulator?","Zener Diode","LED","BJT","SCR","Zener Diode"),
("ECE","Which theorem simplifies complex circuits?","Thevenin’s Theorem","Newton’s Law","Pascal’s Law","Hooke’s Law","Thevenin’s Theorem"),
("ECE","Nyquist theorem relates to?","Sampling","Voltage","Resistance","Power","Sampling"),
("ECE","Which filter passes low frequencies?","High Pass","Band Pass","Low Pass","Band Stop","Low Pass"),
("ECE","Which gate is universal gate?","AND","OR","NAND","XOR","NAND"),
("ECE","Which device converts AC to AC?","Rectifier","Transformer","Oscillator","Amplifier","Transformer"),
("ECE","Unit of power?","Volt","Watt","Ampere","Ohm","Watt"),
("ECE","Which component opposes change in current?","Resistor","Capacitor","Inductor","Battery","Inductor"),
("ECE","Which type of signal is continuous?","Digital","Analog","Binary","Pulse","Analog"),
("ECE","Which coding technique detects error?","Parity Bit","ASCII","Unicode","BCD","Parity Bit"),
("ECE","Which device is used in rectifier circuit?","Diode","Resistor","Inductor","Capacitor","Diode"),
("ECE","Which instrument measures current?","Voltmeter","Ammeter","Ohmmeter","Wattmeter","Ammeter"),
("ECE","Which is full form of ADC?","Analog to Digital Converter","Advanced Digital Circuit","Automatic Data Circuit","None","Analog to Digital Converter"),
("ECE","Which transistor has three terminals?","BJT","FET","MOSFET","All","All"),
("ECE","Which communication uses electromagnetic waves?","Optical Fiber","Wireless","Wired","Cable","Wireless"),
("ECE","Which logic gate inverts input?","AND","OR","NOT","XOR","NOT"),
("ECE","Which law states induced EMF opposes cause?","Faraday’s Law","Lenz’s Law","Ohm’s Law","Kirchhoff’s Law","Lenz’s Law"),
("ECE","Unit of magnetic flux?","Tesla","Weber","Henry","Farad","Weber"),
("ECE","Which oscillator produces sine wave?","RC Oscillator","Square Wave Generator","Clipper","Clamp","RC Oscillator"),
("ECE","Which semiconductor device is light sensitive?","Photodiode","LED","BJT","SCR","Photodiode"),
("ECE","Which modulation varies amplitude?","FM","AM","PM","PCM","AM"),
("ECE","Which device converts mechanical to electrical energy?","Motor","Generator","Transformer","Battery","Generator"),
("ECE","Which is digital logic family?","TTL","RC","LC","RL","TTL"),
("ECE","Which system uses binary digits?","Analog","Digital","Hybrid","Mechanical","Digital"),
("ECE","Which device controls large power using small signal?","Relay","Transistor","Resistor","Capacitor","Transistor"),
("ECE","Which is SI unit of charge?","Coulomb","Volt","Ohm","Tesla","Coulomb"),
("ECE","Which circuit produces clock pulses?","Oscillator","Amplifier","Rectifier","Filter","Oscillator"),
("ECE","Which component blocks DC and passes AC?","Capacitor","Resistor","Inductor","Battery","Capacitor"),
("ECE","Which device is used in switching circuits?","SCR","Resistor","Capacitor","Transformer","SCR")

]


# ========================= MECH (50) =========================

mech_questions = [

("MECH","Unit of force?","Newton","Pascal","Joule","Watt","Newton"),
("MECH","Unit of pressure?","Pascal","Newton","Joule","Volt","Pascal"),
("MECH","SI unit of energy?","Joule","Watt","Newton","Pascal","Joule"),
("MECH","Unit of power?","Watt","Joule","Newton","Pascal","Watt"),
("MECH","Which cycle is used in petrol engine?","Diesel Cycle","Otto Cycle","Rankine Cycle","Brayton Cycle","Otto Cycle"),
("MECH","Which cycle is used in diesel engine?","Otto Cycle","Diesel Cycle","Carnot Cycle","Rankine Cycle","Diesel Cycle"),
("MECH","Which cycle has highest efficiency?","Otto","Diesel","Carnot","Rankine","Carnot"),
("MECH","Unit of torque?","Nm","Watt","Pascal","Joule","Nm"),
("MECH","Which stress is caused by pulling force?","Compressive","Tensile","Shear","Bending","Tensile"),
("MECH","Which stress is due to torsion?","Shear","Tensile","Compressive","Bending","Shear"),
("MECH","Which machine tool is used for turning?","Lathe","Drilling","Milling","Grinding","Lathe"),
("MECH","Which machine tool is used for drilling holes?","Lathe","Drill","Shaper","Planer","Drill"),
("MECH","Which process improves hardness of steel?","Annealing","Normalizing","Hardening","Tempering","Hardening"),
("MECH","Which property resists deformation?","Strength","Density","Color","Mass","Strength"),
("MECH","Unit of temperature?","Kelvin","Coulomb","Volt","Ohm","Kelvin"),
("MECH","Which metal is lightweight?","Steel","Copper","Aluminum","Iron","Aluminum"),
("MECH","Which gear transmits motion at right angle?","Spur","Helical","Bevel","Rack","Bevel"),
("MECH","Which fluid property resists flow?","Density","Viscosity","Pressure","Volume","Viscosity"),
("MECH","Unit of viscosity?","Pa.s","Newton","Watt","Joule","Pa.s"),
("MECH","Which device converts heat energy to mechanical energy?","Pump","Engine","Compressor","Fan","Engine"),
("MECH","Which engine works on Rankine cycle?","Steam Engine","Diesel Engine","Petrol Engine","Electric Motor","Steam Engine"),
("MECH","Which engine uses compression ignition?","Petrol","Diesel","Steam","Electric","Diesel"),
("MECH","Which device lifts water?","Lathe","Pump","Motor","Engine","Pump"),
("MECH","Which is renewable energy source?","Coal","Diesel","Solar","Petrol","Solar"),
("MECH","Which law relates pressure and volume?","Boyle’s Law","Ohm’s Law","Newton’s Law","Hooke’s Law","Boyle’s Law"),
("MECH","Which material is used for cutting tools?","Wood","High Speed Steel","Plastic","Rubber","High Speed Steel"),
("MECH","Which process joins metals permanently?","Casting","Welding","Drilling","Turning","Welding"),
("MECH","Which casting uses sand mold?","Die Casting","Sand Casting","Investment Casting","Shell Casting","Sand Casting"),
("MECH","Which stress occurs due to bending moment?","Tensile","Shear","Bending","Compressive","Bending"),
("MECH","Which instrument measures diameter precisely?","Vernier Caliper","Scale","Protractor","Gauge","Vernier Caliper"),
("MECH","Which engine part converts reciprocating motion to rotary motion?","Crankshaft","Valve","Piston","Cylinder","Crankshaft"),
("MECH","Which thermodynamic law deals with entropy?","Zeroth","First","Second","Third","Second"),
("MECH","Which machine uses reciprocating motion?","Shaper","Lathe","Grinder","Drill","Shaper"),
("MECH","Which fluid machine increases pressure?","Pump","Turbine","Fan","Blower","Pump"),
("MECH","Which turbine uses water energy?","Gas Turbine","Steam Turbine","Hydraulic Turbine","Wind Turbine","Hydraulic Turbine"),
("MECH","Which device converts mechanical to electrical energy?","Motor","Generator","Pump","Compressor","Generator"),
("MECH","Which property measures hardness?","Brinell Test","Tensile Test","Impact Test","Fatigue Test","Brinell Test"),
("MECH","Which joint is temporary?","Welded Joint","Riveted Joint","Bolted Joint","Soldered Joint","Bolted Joint"),
("MECH","Which is SI unit of density?","kg/m³","N/m²","Watt","Joule","kg/m³"),
("MECH","Which machine removes material by abrasion?","Lathe","Drill","Grinding Machine","Shaper","Grinding Machine"),
("MECH","Which device compresses air?","Pump","Compressor","Turbine","Fan","Compressor"),
("MECH","Which fuel has highest calorific value?","Diesel","Petrol","Hydrogen","Coal","Hydrogen"),
("MECH","Which process softens metal?","Hardening","Annealing","Normalizing","Tempering","Annealing"),
("MECH","Which gear is used for parallel shafts?","Bevel","Spur","Worm","Rack","Spur"),
("MECH","Which type of stress acts perpendicular to surface?","Shear","Tensile","Normal","Bending","Normal"),
("MECH","Which device measures pressure?","Manometer","Thermometer","Barometer","Voltmeter","Manometer"),
("MECH","Which engine component controls air-fuel mixture?","Carburetor","Crankshaft","Flywheel","Radiator","Carburetor"),
("MECH","Which process removes internal stresses?","Annealing","Hardening","Forging","Casting","Annealing"),
("MECH","Which type of load is gradually applied?","Sudden Load","Impact Load","Gradual Load","Shock Load","Gradual Load"),
("MECH","Which device converts pressure energy to kinetic energy?","Nozzle","Pump","Motor","Fan","Nozzle")

]


eee_questions = [

("EEE","Unit of electric current?","Volt","Ampere","Ohm","Watt","Ampere"),
("EEE","Unit of power?","Watt","Volt","Ohm","Henry","Watt"),
("EEE","Which law states V = IR?","Faraday","Ohm","Kirchhoff","Lenz","Ohm"),
("EEE","Which device converts AC to DC?","Inverter","Rectifier","Transformer","Motor","Rectifier"),
("EEE","Which machine converts electrical to mechanical energy?","Generator","Motor","Transformer","Rectifier","Motor"),
("EEE","Which machine converts mechanical to electrical energy?","Motor","Generator","Battery","Inverter","Generator"),
("EEE","Unit of resistance?","Volt","Ampere","Ohm","Tesla","Ohm"),
("EEE","Which is a step-up transformer?","Ns < Np","Ns > Np","Ns = Np","None","Ns > Np"),
("EEE","Which device stores magnetic energy?","Capacitor","Inductor","Resistor","Battery","Inductor"),
("EEE","Which motor works on DC supply?","Induction Motor","DC Motor","Synchronous Motor","Alternator","DC Motor"),
("EEE","Which device controls high voltage?","Relay","Circuit Breaker","Switch","Fuse","Circuit Breaker"),
("EEE","Unit of frequency?","Hertz","Tesla","Henry","Volt","Hertz"),
("EEE","Which motor runs at synchronous speed?","DC Motor","Induction Motor","Synchronous Motor","Stepper","Synchronous Motor"),
("EEE","Which loss occurs in transformer core?","Copper Loss","Hysteresis Loss","Mechanical Loss","Windage Loss","Hysteresis Loss"),
("EEE","Which law states induced EMF opposes cause?","Faraday","Lenz","Ohm","Kirchhoff","Lenz"),
("EEE","Which power plant uses coal?","Thermal","Hydro","Nuclear","Solar","Thermal"),
("EEE","Which device protects from overcurrent?","Fuse","Capacitor","Transformer","Motor","Fuse"),
("EEE","Unit of capacitance?","Farad","Henry","Tesla","Weber","Farad"),
("EEE","Which instrument measures power?","Voltmeter","Ammeter","Wattmeter","Ohmmeter","Wattmeter"),
("EEE","Which motor is self-starting?","Synchronous","Induction","DC Shunt","Stepper","Induction"),
("EEE","Which device converts DC to AC?","Rectifier","Inverter","Transformer","Relay","Inverter"),
("EEE","Which conductor has low resistivity?","Copper","Iron","Wood","Plastic","Copper"),
("EEE","Which quantity is measured in kWh?","Voltage","Energy","Power","Current","Energy"),
("EEE","Which law is used in mesh analysis?","Kirchhoff’s Voltage Law","Ohm’s Law","Lenz’s Law","Faraday’s Law","Kirchhoff’s Voltage Law"),
("EEE","Which motor is used in electric trains?","DC Series Motor","Stepper Motor","Synchronous Motor","Servo Motor","DC Series Motor"),
("EEE","Which power plant is renewable?","Thermal","Diesel","Solar","Coal","Solar"),
("EEE","Which device changes voltage level?","Transformer","Motor","Generator","Battery","Transformer"),
("EEE","Which factor improves power factor?","Capacitor","Resistor","Inductor","Fuse","Capacitor"),
("EEE","Which unit measures inductance?","Henry","Farad","Ohm","Tesla","Henry"),
("EEE","Which machine produces AC power?","Alternator","Motor","Rectifier","Inverter","Alternator"),
("EEE","Which device isolates faulty section?","Relay","Transformer","Motor","Capacitor","Relay"),
("EEE","Which quantity is constant in series circuit?","Voltage","Current","Resistance","Power","Current"),
("EEE","Which device limits current?","Resistor","Capacitor","Inductor","Battery","Resistor"),
("EEE","Which plant uses flowing water?","Thermal","Hydro","Nuclear","Diesel","Hydro"),
("EEE","Which instrument measures insulation resistance?","Megger","Voltmeter","Ammeter","Wattmeter","Megger"),
("EEE","Which machine is used in power generation?","Generator","Motor","Rectifier","Battery","Generator"),
("EEE","Which device smoothens DC output?","Filter","Rectifier","Transformer","Relay","Filter"),
("EEE","Which motor has high starting torque?","DC Series","DC Shunt","Synchronous","Stepper","DC Series"),
("EEE","Which unit measures electric charge?","Coulomb","Volt","Ohm","Tesla","Coulomb"),
("EEE","Which power factor is ideal?","0","0.5","1","2","1"),
("EEE","Which law relates magnetic field and current?","Ampere’s Law","Ohm’s Law","Newton’s Law","Boyle’s Law","Ampere’s Law"),
("EEE","Which system transmits power long distance?","HVAC","LVAC","DC Only","Battery","HVAC"),
("EEE","Which type of current changes direction?","DC","AC","Static","Pulse","AC"),
("EEE","Which device converts chemical to electrical energy?","Battery","Motor","Generator","Transformer","Battery"),
("EEE","Which component blocks AC?","Inductor","Capacitor","Resistor","Relay","Inductor"),
("EEE","Which device amplifies electrical signal?","Transistor","Resistor","Capacitor","Fuse","Transistor"),
("EEE","Which effect causes heating in conductor?","Joule Effect","Hall Effect","Skin Effect","Photo Effect","Joule Effect"),
("EEE","Which law relates power, voltage, current?","P = VI","V = IR","E = mc²","F = ma","P = VI"),
("EEE","Which unit measures magnetic flux?","Weber","Tesla","Henry","Volt","Weber"),
("EEE","Which component opposes change in current?","Inductor","Resistor","Capacitor","Fuse","Inductor")

]

civil_questions = [

("CIVIL","Unit of force?","Newton","Pascal","Joule","Watt","Newton"),
("CIVIL","Unit of stress?","Pascal","Newton","Joule","Watt","Pascal"),
("CIVIL","Which test measures concrete strength?","Slump Test","Compression Test","Tensile Test","Impact Test","Compression Test"),
("CIVIL","Which material is used in cement manufacturing?","Limestone","Copper","Iron","Aluminum","Limestone"),
("CIVIL","Which instrument measures angles in surveying?","Theodolite","Level Tube","Chain","Compass","Theodolite"),
("CIVIL","Which soil has highest bearing capacity?","Clay","Silt","Sand","Gravel","Gravel"),
("CIVIL","Which cement is used for rapid strength gain?","OPC","PPC","Rapid Hardening Cement","White Cement","Rapid Hardening Cement"),
("CIVIL","Unit of work?","Joule","Watt","Pascal","Newton","Joule"),
("CIVIL","Which test determines workability of concrete?","Slump Test","Compression Test","Impact Test","Tension Test","Slump Test"),
("CIVIL","Which structure transfers load to ground?","Beam","Column","Foundation","Slab","Foundation"),
("CIVIL","Which type of load is permanent?","Dead Load","Live Load","Wind Load","Impact Load","Dead Load"),
("CIVIL","Which is coarse aggregate?","Sand","Gravel","Cement","Silt","Gravel"),
("CIVIL","Which is fine aggregate?","Sand","Stone","Brick","Steel","Sand"),
("CIVIL","Which structure resists bending?","Beam","Column","Footing","Foundation","Beam"),
("CIVIL","Which test determines soil bearing capacity?","SPT","Slump Test","Compression Test","Tensile Test","SPT"),
("CIVIL","Which material is used for reinforcement?","Steel","Wood","Plastic","Glass","Steel"),
("CIVIL","Which type of foundation is shallow?","Pile","Raft","Isolated Footing","Caisson","Isolated Footing"),
("CIVIL","Which test checks cement fineness?","Sieve Test","Slump Test","Impact Test","Tension Test","Sieve Test"),
("CIVIL","Which structure carries traffic?","Bridge","Dam","Tunnel","Canal","Bridge"),
("CIVIL","Which type of beam is fixed at both ends?","Simply Supported","Cantilever","Fixed Beam","Continuous Beam","Fixed Beam"),
("CIVIL","Which test measures water content in soil?","Oven Dry Test","Slump Test","SPT","Impact Test","Oven Dry Test"),
("CIVIL","Which is used in road construction?","Bitumen","Cement","Sand","Clay","Bitumen"),
("CIVIL","Which unit measures discharge?","m³/s","Pascal","Newton","Joule","m³/s"),
("CIVIL","Which structure stores water?","Dam","Bridge","Tunnel","Road","Dam"),
("CIVIL","Which stress acts perpendicular to surface?","Normal Stress","Shear Stress","Torsion","Bending","Normal Stress"),
("CIVIL","Which is used for leveling?","Dump Level","Theodolite","Chain","Compass","Dump Level"),
("CIVIL","Which test measures tensile strength of steel?","UTM Test","Slump Test","SPT","Oven Test","UTM Test"),
("CIVIL","Which foundation is deep foundation?","Pile Foundation","Raft","Isolated Footing","Slab","Pile Foundation"),
("CIVIL","Which type of cement is waterproof?","Hydrophobic Cement","OPC","PPC","White Cement","Hydrophobic Cement"),
("CIVIL","Which unit measures density?","kg/m³","N/m²","Joule","Watt","kg/m³"),
("CIVIL","Which structural member carries compressive load?","Column","Beam","Slab","Footing","Column"),
("CIVIL","Which is used in sewage treatment?","Sedimentation Tank","Beam","Column","Slab","Sedimentation Tank"),
("CIVIL","Which load varies with time?","Live Load","Dead Load","Self Weight","Static Load","Live Load"),
("CIVIL","Which type of dam is concrete dam?","Gravity Dam","Earth Dam","Rock Fill Dam","Timber Dam","Gravity Dam"),
("CIVIL","Which property measures hardness of aggregate?","Impact Test","Slump Test","Tension Test","Oven Test","Impact Test"),
("CIVIL","Which is main ingredient of concrete?","Cement","Plastic","Wood","Glass","Cement"),
("CIVIL","Which type of road is flexible pavement?","Bituminous Road","Concrete Road","Steel Road","Brick Road","Bituminous Road"),
("CIVIL","Which unit measures pressure?","Pascal","Newton","Joule","Watt","Pascal"),
("CIVIL","Which type of stress acts parallel to surface?","Shear Stress","Normal Stress","Bending","Tension","Shear Stress"),
("CIVIL","Which test determines slump value?","Slump Cone Test","SPT","UTM","Oven Test","Slump Cone Test"),
("CIVIL","Which soil is most compressible?","Clay","Gravel","Sand","Rock","Clay"),
("CIVIL","Which structure conveys water?","Canal","Bridge","Dam","Road","Canal"),
("CIVIL","Which is used in plastering?","Cement Mortar","Concrete","Bitumen","Steel","Cement Mortar"),
("CIVIL","Which structure resists water pressure?","Retaining Wall","Beam","Column","Slab","Retaining Wall"),
("CIVIL","Which instrument measures rainfall?","Rain Gauge","Thermometer","Barometer","Anemometer","Rain Gauge"),
("CIVIL","Which test determines compaction?","Proctor Test","Slump Test","SPT","Impact Test","Proctor Test"),
("CIVIL","Which is example of hydraulic structure?","Dam","Bridge","Road","Tunnel","Dam"),
("CIVIL","Which material increases concrete strength?","Admixture","Sand","Water","Clay","Admixture"),
("CIVIL","Which member distributes load to column?","Beam","Footing","Slab","Pile","Beam"),
("CIVIL","Which structure provides support to roof?","Column","Beam","Slab","Foundation","Beam")

]


it_questions = [

("IT","Which protocol is used to transfer web pages?","FTP","HTTP","SMTP","SNMP","HTTP"),
("IT","Which device connects multiple networks?","Switch","Hub","Router","Repeater","Router"),
("IT","Which database language is used to retrieve data?","DDL","DML","SQL","DCL","SQL"),
("IT","Which command retrieves records in SQL?","INSERT","DELETE","SELECT","UPDATE","SELECT"),
("IT","Which is a NoSQL database?","MySQL","Oracle","MongoDB","PostgreSQL","MongoDB"),
("IT","Which protocol sends email?","HTTP","SMTP","FTP","DNS","SMTP"),
("IT","Which protocol receives email?","POP3","HTTP","FTP","SNMP","POP3"),
("IT","Which port is used for HTTPS?","21","25","443","110","443"),
("IT","Which attack steals user session?","Phishing","Session Hijacking","Spoofing","Scanning","Session Hijacking"),
("IT","Which encryption is symmetric?","RSA","AES","ECC","DSA","AES"),
("IT","Which firewall filters traffic?","Network Firewall","Compiler","IDE","Browser","Network Firewall"),
("IT","Which topology connects all nodes to central hub?","Bus","Ring","Star","Mesh","Star"),
("IT","Which IP version uses 128-bit address?","IPv4","IPv6","Both","None","IPv6"),
("IT","Which device forwards data based on MAC address?","Router","Switch","Hub","Bridge","Switch"),
("IT","Which is cloud computing service model?","IaaS","LAN","WAN","PAN","IaaS"),
("IT","Which company provides AWS?","Microsoft","Amazon","Google","IBM","Amazon"),
("IT","Which protocol resolves IP to MAC?","DNS","ARP","FTP","SMTP","ARP"),
("IT","Which is used for virtualization?","VMware","HTML","CSS","MySQL","VMware"),
("IT","Which OS is open source?","Windows","Linux","macOS","DOS","Linux"),
("IT","Which malware demands ransom?","Virus","Trojan","Ransomware","Spyware","Ransomware"),
("IT","Which is relational database?","MongoDB","Cassandra","MySQL","Redis","MySQL"),
("IT","Which layer encrypts data in OSI?","Presentation","Transport","Network","Physical","Presentation"),
("IT","Which HTTP method submits form data?","GET","POST","PUT","DELETE","POST"),
("IT","Which tool is used for version control?","Git","Chrome","Linux","Apache","Git"),
("IT","Which is programming language for web backend?","HTML","CSS","Python","XML","Python"),
("IT","Which is primary key property?","Unique","Duplicate","Null","Optional","Unique"),
("IT","Which protocol is connectionless?","TCP","UDP","HTTP","SMTP","UDP"),
("IT","Which is secure shell protocol?","SSH","FTP","HTTP","ARP","SSH"),
("IT","Which database constraint ensures uniqueness?","NOT NULL","UNIQUE","FOREIGN","CHECK","UNIQUE"),
("IT","Which technology is used for styling web pages?","HTML","CSS","Python","SQL","CSS"),
("IT","Which protocol translates domain to IP?","DNS","FTP","SMTP","HTTP","DNS"),
("IT","Which device boosts signal strength?","Repeater","Router","Switch","Bridge","Repeater"),
("IT","Which attack tricks user via fake email?","Phishing","Spoofing","Sniffing","Scanning","Phishing"),
("IT","Which cloud model is private to organization?","Public Cloud","Private Cloud","Hybrid Cloud","Community Cloud","Private Cloud"),
("IT","Which database stores data in tables?","Relational DB","NoSQL","File System","Blockchain","Relational DB"),
("IT","Which command removes table in SQL?","DROP","DELETE","REMOVE","CLEAR","DROP"),
("IT","Which protocol is used for file transfer?","FTP","HTTP","SMTP","ARP","FTP"),
("IT","Which tool monitors network traffic?","Wireshark","Photoshop","Excel","PowerPoint","Wireshark"),
("IT","Which is strong password practice?","123456","Password","Mixed Characters","ABC123","Mixed Characters"),
("IT","Which port is used for FTP?","21","22","80","443","21"),
("IT","Which technology provides containerization?","Docker","Git","MySQL","Apache","Docker"),
("IT","Which SQL clause filters records?","WHERE","ORDER BY","GROUP BY","SELECT","WHERE"),
("IT","Which authentication uses two methods?","Single Factor","Two-Factor","Open Access","Guest","Two-Factor"),
("IT","Which tool automates deployment?","Jenkins","Chrome","Excel","Word","Jenkins"),
("IT","Which protocol provides secure web?","HTTP","HTTPS","FTP","SMTP","HTTPS"),
("IT","Which data structure stores key-value pairs?","Array","Stack","Dictionary","Queue","Dictionary"),
("IT","Which is example of scripting language?","C","Java","Python","Assembly","Python"),
("IT","Which is network security device?","Firewall","Monitor","Printer","Keyboard","Firewall"),
("IT","Which service provides remote repository hosting?","GitHub","Chrome","Windows","Linux","GitHub"),
("IT","Which model describes cloud deployment types?","Public/Private/Hybrid","LAN/WAN","OSI","TCP/IP","Public/Private/Hybrid")

]



questions = cse_questions + ece_questions + mech_questions + eee_questions + civil_questions + it_questions 
# Insert
c.executemany("""
INSERT INTO questions (department, question, option1, option2, option3, option4, answer)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", questions)

conn.commit()
conn.close()

print("✅ 150 Questions Inserted Successfully (50 per branch)")
